### ISSUE TITLE
xms_rest_conf.pl not working with XMS 3.0

### ISSUE THREAD

**Issue by antonroman** [Dialogic/dialogic-rest-perl#1]
Hi,

I tested the script xms_rest_conf.pl directly using the Dialogic WebRTC reference client with XMS 3.0. The call is answered but it seems it's not added to the conference. I open this issue just to ask if this script is supposed to work in 3.0 or there might be some difference in the REST API which could prevent it from working properly.  The helloworld example works fine and if I call conf_demo from the reference client also works as expected.
 I'm attaching the [logs](http://pastebin.com/rVaRqGM8) just in case it helps. I'll keep checking it on my side as a script we did using the conference resource and it's not working well with 3.0.  

Thanks

**Comment by vfpuglia** [comment]
I never see the conf join get executed in your logs - so from your trace, after the debug out: 

Handling call response 1
Handling call response 2

We should see: 
print "Incoming call from '$caller_name' connected. Joining to conference...\n";

But instead it's trying to play a file: 
Sending HTTP PUT for 'http://10.1.20.252:81/default/conferences/e609cecb-aced-4f5f-8160-d1544a6b847d?appid=app' with content:
<web_service version="1.0"><conference><conf_action><play max_time="20s"><play_source video_uri="file://verification/Dialogic_networkFuel.vid" video_type="video/x-vid"/></play></conf_action></conference></web_service>

Which is not part of the conf script - did you modify?

**Comment by antonroman** [comment]
Sorry,

 it was my fault, I thought  I had done checkout to get the original file
but I dind't. It works. Sorry for the noise.

Thanks

**Comment by vfpuglia** [comment]
No worries - glad it works 

Thanks
Vince
